import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import ChatBot from "./Components/ChatBot";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Figma Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <ChatBot/>
      <Navbar className='overflow-hidden'/>
      <body className={inter.className} suppressHydrationWarning>{children}</body>
      <Footer  className='overflow-hidden'/>
    </html>
  );
}
